config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zooApp.urls', namespace='zooApp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zooApp/urls.py
from django.urls import path

from zooApp.apps import ZooappConfig
from zooApp.views import CategoryListView, DogsListView, DogDetailView, DogUpdateView, DogCreateView, \
    DogDeleteView, CategoryCreateView, CategoryUpdateView, settings, CategoryDeleteView, BlogCreateView, BlogListView, \
    BlogUpdateView, BlogDetailView, BlogDeleteView, BlogUnpublishedListView

app_name = ZooappConfig.name

urlpatterns = [

    path('settings/', settings, name='settings'),

    path('category/', CategoryListView.as_view(), name='category'),
    path('category/create/', CategoryCreateView.as_view(), name='create_category'),
    path('<int:pk>category/update/', CategoryUpdateView.as_view(), name='update_category'),
    path('<int:pk>category/delete/', CategoryDeleteView.as_view(), name='delete_category'),

    path('create/dog/', DogCreateView.as_view(), name='create_dog'),
    path('<int:pk>dogs/', DogsListView.as_view(), name='dogs'),
    path('<int:pk>dog/detail/', DogDetailView.as_view(), name='dog_detail'),
    path('<int:pk>dog/update/', DogUpdateView.as_view(), name='update_dog'),
    path('<int:pk>dog/delete/', DogDeleteView.as_view(), name='delete_dog'),

    path('', BlogListView.as_view(), name='main'),
    path('unpublished', BlogUnpublishedListView.as_view(), name='unpublished'),
    path('blog/create/', BlogCreateView.as_view(), name='create_blog'),
    path('<int:pk>blog/update/', BlogUpdateView.as_view(), name='update_blog'),
    path('<int:pk>blog/detail/', BlogDetailView.as_view(), name='detail_blog'),
    path('<int:pk>blog/delete/', BlogDeleteView.as_view(), name='delete_blog'),

]

zooApp/models.py
from django.db import models
from django.utils.text import slugify

NULLABLE = {
    'blank': True,
    'null': True
}


class User(models.Model):
    first_name = models.CharField(**NULLABLE, max_length=30, verbose_name='Имя')
    last_name = models.CharField(**NULLABLE, max_length=30, verbose_name='Фамилия')
    age = models.IntegerField(**NULLABLE, verbose_name='Возраст')
    photo = models.ImageField(**NULLABLE, upload_to='user/', verbose_name='Фото')
    email = models.EmailField(**NULLABLE, verbose_name='Почта')

    def __str__(self):
        return f'{self.first_name}, {self.last_name}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    photo = models.ImageField(**NULLABLE, upload_to='category/', verbose_name='Фото')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Порода'
        verbose_name_plural = 'Породы'


class Dog(models.Model):
    name = models.CharField(max_length=50, verbose_name='Кличка')
    age = models.IntegerField(**NULLABLE, verbose_name='Возраст')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    photo = models.ImageField(**NULLABLE, upload_to='dog/', verbose_name='Фото')
    price = models.IntegerField(verbose_name='Стоимость')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Порода')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Собака'
        verbose_name_plural = 'Собаки'


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.SlugField(max_length=50, verbose_name='slug')
    content = models.TextField(verbose_name='Содержимое')
    photo = models.ImageField(**NULLABLE, upload_to='blog_previews/', verbose_name='Превью')
    view_count = models.IntegerField(default=0, verbose_name='Просмотры')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    published = models.BooleanField(default=False, verbose_name='Публикация')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

zooApp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from transliterate import translit
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from zooApp.models import Category, Dog, Blog


class CategoryListView(ListView):
    """Наследовался от модели Category"""
    model = Category
    """Указал максимальное кол-во карточек на странице (в CBV передает page_obj в контексте под капотом)"""
    paginate_by = 10
    """Функция для передачи доп информации (контекста) в шаблон"""

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        """Добавили поле title и вернули с помощью return"""
        context['title'] = 'Породы'
        return context


"""Класс для создания породы"""


class CategoryCreateView(CreateView):
    model = Category
    """Поля для которые нужно заполнить при создании"""
    fields = ('name', 'description', 'photo')
    """Ссылка по умолчанию по которой пользователь будет переходить после создания породы"""
    success_url = reverse_lazy('zooApp:category')


"""Класс для редактирования породы"""


class CategoryUpdateView(UpdateView):
    model = Category
    fields = ('name', 'description', 'photo')
    success_url = reverse_lazy('zooApp:category')


"""Класс удаление породы"""


class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('zooApp:category')


"""Метод ссылающийся на шаблон настройки"""


def settings(request):
    context = {
        'title': 'Настройки'
    }
    return render(request, 'zooApp/settings.html')


"""Список собак"""


class DogsListView(ListView):
    model = Dog
    paginate_by = 10

    """Передача контекста"""

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Собаки'
        return context

    def get_queryset(self):
        """Извлекаем значение первичного ключа"""
        category_pk = self.kwargs['pk']
        """Выполняем запрос к модели Dog и фильтруем по pk"""
        return Dog.objects.filter(category__pk=category_pk)


"""Класс выводит конкретную собаку"""


class DogDetailView(DetailView):
    model = Dog


class DogCreateView(CreateView):
    model = Dog
    fields = ('name', 'age', 'description', 'photo', 'price', 'category')

    success_url = reverse_lazy('zooApp:dog_detail')

    """Метод передает pk для того что бы мы могли попасть в карточку только что созданной собаки"""

    def get_success_url(self):
        """Получаем pk"""
        object_id = self.object.pk
        """Передаем pk переходя по url"""
        detail_url = reverse_lazy('zooApp:dog_detail', kwargs={'pk': object_id})
        return detail_url


class DogUpdateView(UpdateView):
    model = Dog
    fields = ('name', 'age', 'description', 'photo', 'price', 'category')
    success_url = reverse_lazy('zooApp:dog_detail')

    def get_success_url(self):
        object_id = self.object.pk
        detail_url = reverse_lazy('zooApp:dog_detail', kwargs={'pk': object_id})
        return detail_url


class DogDeleteView(DeleteView):
    model = Dog
    success_url = reverse_lazy('zooApp:category')


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'photo', 'published',)
    success_url = reverse_lazy('zooApp:detail_blog')

    def get_success_url(self):
        object_id = self.object.pk
        detail_url = reverse_lazy('zooApp:detail_blog', kwargs={'pk': object_id})
        return detail_url


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'photo', 'published',)
    success_url = reverse_lazy('zooApp:detail_blog')

    def get_success_url(self):
        object_id = self.object.pk
        detail_url = reverse_lazy('zooApp:detail_blog', kwargs={'pk': object_id})
        return detail_url


class BlogListView(ListView):
    model = Blog
    template_name = 'zooApp/main_list_true.html'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная Страница'

        return context


"""Класс для не опубликованных блогов"""


class BlogUnpublishedListView(ListView):
    model = Blog
    paginate_by = 10
    template_name = 'zooApp/blog_unpublished.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Не опубликовано'
        return context


class BlogDetailView(DetailView):
    model = Blog

    """Метод для отслеживания просмотров"""

    def get(self, request, *args, **kwargs):
        blog = self.get_object()

        # Увеличиваем счетчик просмотров
        blog.view_count += 1
        blog.save()

        return super().get(request, *args, **kwargs)

    """Создание человекочитаймого slug переводит с русского языка на английский"""

    def create_slug(self, title):
        return translit(title, 'ru', reversed=True)

    def get_queryset(self):
        queryset = super().get_queryset()
        for blog in queryset:
            blog.slug = self.create_slug(blog.title)
            blog.save()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Публикация'
        return context


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('zooApp:main')

zooApp/templates/zooApp/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            ElectroDen
            <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

zooApp/templates/zooApp/blog_confirm_delete.html
{% extends 'zooApp/base.html' %}
{% include 'zooApp/includes/inc_menu.html' %}
{% block content %}
{% include 'zooApp/includes/inc_menu.html' %}
{% include 'zooApp/includes/inc_delete.html' %}
{% endblock %}

zooApp/templates/zooApp/blog_detail.html
{% extends 'zooApp/base.html' %}

{% block content %}
{% include 'zooApp/includes/inc_menu.html' %}
{% load my_tags %}
<tr>
    <h1>Карточка собаки</h1>
</tr>
<div class="image-container">


    <img src="{{ object.photo|mymedia }}" width="200" height="200">
</div>
<div class="col-lg-9 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <table class="table table-striped">
                <tr>
                    <td class="w-25">Заголовок</td>
                    <td>{{ object.title }}</td>
                </tr>
                <tr>
                    <td class="w-25">slug</td>
                    <td>{{ object.slug }}</td>
                </tr>
                <tr>
                    <td class="w-25">Описание</td>
                    <td>{{ object.content }}</td>
                </tr>

                <tr>
                    <td class="w-25">Просмотры</td>
                    <td>{{ object.view_count }}</td>

                </tr>


                <tr>
                    <td class="w-25">Время создания</td>
                    <td>{{ object.created_at }}</td>
                </tr>

                <tr>
                    <td class="w-25">Публикация</td>
                    {% if object.published %}
                    <td>Опубликовано</td>
                    {% else %}
                    <td>Не опубликовано</td>
                    {% endif %}
                </tr>

            </table>

            <a href="{% url 'zooApp:update_blog' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
            <a href="{% url 'zooApp:delete_blog' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">удалить</a>

        </div>
    </div>
</div>
{% endblock %}

zooApp/templates/zooApp/blog_form.html
{% extends 'zooApp/base.html' %}

{% block content %}
{% include 'zooApp/includes/inc_menu.html' %}
{% include 'zooApp/includes/inc_form.html' %}
{% endblock %}

zooApp/templates/zooApp/blog_unpublished.html
{% extends 'zooApp/base.html' %}

{% block content%}
{% include 'zooApp/includes/inc_menu.html' %}

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:create_blog' %}">Создать Публикацию</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:main' %}">Опубликованные</a>

    </nav>
</div>

{% load my_tags %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"></h1>
</div>
<div class="container">
    <h1>{{ title }}</h1>

    <div class="row text-center">
        {% for object in object_list %}
        {% if object.published == False %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">

                    <img src="{{ object.photo|mymedia }}" width="200" height="200">
                    {% if object.content %}
                    <li>{{ object.content|truncatechars:50 }}</li>
                    {% endif %}

                    <a href="{% url 'zooApp:detail_blog' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Перейти</a>

                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>

</div>

{% include 'zooApp/includes/inc_paginate.html' %}

{% endblock %}

zooApp/templates/zooApp/category_confirm_delete.html
{% extends 'zooApp/base.html' %}
{% include 'zooApp/includes/inc_menu.html' %}
{% block content %}
{% include 'zooApp/includes/inc_menu.html' %}
{% include 'zooApp/includes/inc_delete.html' %}
{% endblock %}

zooApp/templates/zooApp/category_form.html
{% extends 'zooApp/base.html' %}
{% include 'zooApp/includes/inc_menu.html' %}
{% block content %}
{% include 'zooApp/includes/inc_menu.html' %}
<div class="container">
    <main>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-5">

                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Редактирование</h4>
                    <form class="needs-validation" novalidate>
                        {{ form.as_p }}

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif%}
                        </button>
                    </form>

                </div>
            </div>
        </form>
    </main>
</div>
{% endblock %}

zooApp/templates/zooApp/category_list.html
{% extends 'zooApp/base.html' %}

{% block content %}
{% include 'zooApp/includes/inc_menu.html' %}

{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"></h1>
</div>
<div class="container">
    <h1>{{ title }}</h1>
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">

                    <img src="{{ object.photo|mymedia }}" width="200" height="200">
                    {% if object.description %}
                    <li>{{ object.description|truncatechars:50 }}</li>
                    {% endif%}

                    <a href="{% url 'zooApp:dogs' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Перейти</a>

                    <a href="{% url 'zooApp:update_category' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
                    <a href="{% url 'zooApp:delete_category' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">удалить</a>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% include 'zooApp/includes/inc_paginate.html' %}

{% endblock %}

zooApp/templates/zooApp/dog_confirm_delete.html
{% extends 'zooApp/base.html' %}
{% include 'zooApp/includes/inc_menu.html' %}
{% block content %}
{% include 'zooApp/includes/inc_menu.html' %}
<div class="container">
    <main>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-5">
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Удаление</h4>
                    <form class="needs-validation" novalidate>

                        <hr class="my-4">
                        <p>Вы действительно хотите удалить "{{ object.name }}"?</p>

                        <button class="btn btn-danger btn-lg" type="submit">Удалить</button>
                        <a href="{% url 'zooApp:dogdetail' object.pk %}" class="btn btn-warning">Отмена</a>
                    </form>

                </div>
            </div>
        </form>
    </main>
</div>
{% endblock %}

zooApp/templates/zooApp/dog_detail.html
{% extends 'zooApp/base.html' %}

{% block content %}
{% include 'zooApp/includes/inc_menu.html' %}
{% load my_tags %}
<tr>
    <h1>Карточка собаки</h1>
</tr>
<div class="image-container">


    <img src="{{ object.photo|mymedia }}" width="200" height="200">
</div>
<div class="col-lg-9 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <table class="table table-striped">
                <tr>
                    <td class="w-25">Кличка</td>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <td class="w-25">Порода</td>
                    <td>{{ object.category }}</td>
                </tr>
                <tr>
                    <td class="w-25">Возраст</td>
                    <td>{{ object.age }}</td>
                </tr>

                <tr>
                    <td class="w-25">Описание</td>
                    {% if object.description %}
                    <td>{{ object.description }}</td>
                    {% else %}
                    <td>Нет описания</td>
                    {% endif %}

                </tr>

                <tr>
                    <td class="w-25">Прайс</td>
                    <td>{{ object.price }}</td>
                </tr>

            </table>
            <a href="{% url 'zooApp:update_dog' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
            <a href="{% url 'zooApp:delete_dog' object.pk%}" class="btn btn-lg btn-block btn-outline-primary">удалить</a>
        </div>
    </div>
</div>
{% endblock %}

zooApp/templates/zooApp/dog_list.html
{% extends 'zooApp/base.html' %}

{% block content %}
{% include 'zooApp/includes/inc_menu.html' %}

{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"></h1>
</div>
<div class="container">
    <h1>{{ title }}</h1>
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">

                    <img src="{{ object.photo|mymedia }}" width="200" height="200">
                    {% if object.description %}
                    <li>{{ object.description|truncatechars:50 }}</li>
                    {% endif%}

                    <a href="{% url 'zooApp:dog_detail' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Перейти</a>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% include 'zooApp/includes/inc_paginate.html' %}

{% endblock %}

zooApp/templates/zooApp/main_list.html
{% extends 'zooApp/base.html' %}

{% block content%}
{% include 'zooApp/includes/inc_menu.html' %}

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:createblog' %}">Создать Публикацию</a>
    </nav>
</div>

{% load my_tags %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"></h1>
</div>
<div class="container">
    <h1>{{ title }}</h1>
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">

                    <img src="{{ object.photo|mymedia }}" width="200" height="200">
                    {% if object.content %}
                    <li>{{ object.content|truncatechars:50 }}</li>
                    {% endif %}

                    <a href="{% url 'zooApp:detailblog' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Перейти</a>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

zooApp/templates/zooApp/main_list_true.html
{% extends 'zooApp/base.html' %}

{% block content%}
{% include 'zooApp/includes/inc_menu.html' %}

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:create_blog' %}">Создать Публикацию</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:unpublished' %}">Не опубликованные</a>

    </nav>
</div>

{% load my_tags %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"></h1>
</div>
<div class="container">
    <h1>{{ title }}</h1>

    <div class="row text-center">
        {% for object in object_list %}
        {% if object.published %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">

                    <img src="{{ object.photo|mymedia }}" width="200" height="200">
                    {% if object.content %}
                    <li>{{ object.content|truncatechars:50 }}</li>
                    {% endif %}

                    <a href="{% url 'zooApp:detail_blog' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Перейти</a>

                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>

</div>

{% include 'zooApp/includes/inc_paginate.html' %}

{% endblock %}
{% include 'zooApp/includes/inc_page.html' %}

zooApp/templates/zooApp/settings.html
{% extends 'zooApp/base.html' %}

{% block content%}
{% include 'zooApp/includes/inc_menu.html' %}

<a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:create_dog' %}">Добавить собаку</a>
<a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:create_category' %}">Добавить породу</a>

{% endblock %}