config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zooApp.urls', namespace='zooApp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zooApp/urls.py
from django.urls import path

from zooApp.apps import ZooappConfig
from zooApp.views import CategoryListView, DogsListView, DogDetailView, DogUpdateView, DogCreateView, \
    DogDeleteView, CategoryCreateView, CategoryUpdateView, settings, CategoryDeleteView, BlogCreateView, BlogListView, \
    BlogUpdateView, BlogDetailView, BlogDeleteView, BlogUnpublishedListView

app_name = ZooappConfig.name

urlpatterns = [

    path('settings/', settings, name='settings'),

    path('category/', CategoryListView.as_view(), name='category'),
    path('category/create/', CategoryCreateView.as_view(), name='create_category'),
    path('<int:pk>category/update/', CategoryUpdateView.as_view(), name='update_category'),
    path('<int:pk>category/delete/', CategoryDeleteView.as_view(), name='delete_category'),

    path('create/dog/', DogCreateView.as_view(), name='create_dog'),
    path('<int:pk>dogs/', DogsListView.as_view(), name='dogs'),
    path('<int:pk>dog/detail/', DogDetailView.as_view(), name='dog_detail'),
    path('<int:pk>dog/update/', DogUpdateView.as_view(), name='update_dog'),
    path('<int:pk>dog/delete/', DogDeleteView.as_view(), name='delete_dog'),

    path('', BlogListView.as_view(), name='main'),
    path('unpublished', BlogUnpublishedListView.as_view(), name='unpublished'),
    path('blog/create/', BlogCreateView.as_view(), name='create_blog'),
    path('<int:pk>blog/update/', BlogUpdateView.as_view(), name='update_blog'),
    path('<int:pk>blog/detail/', BlogDetailView.as_view(), name='detail_blog'),
    path('<int:pk>blog/delete/', BlogDeleteView.as_view(), name='delete_blog'),

]

zooApp/models.py
from django.db import models
from django.utils.text import slugify

NULLABLE = {
    'blank': True,
    'null': True
}


class User(models.Model):
    first_name = models.CharField(**NULLABLE, max_length=30, verbose_name='Имя')
    last_name = models.CharField(**NULLABLE, max_length=30, verbose_name='Фамилия')
    age = models.IntegerField(**NULLABLE, verbose_name='Возраст')
    photo = models.ImageField(**NULLABLE, upload_to='user/', verbose_name='Фото')
    email = models.EmailField(**NULLABLE, verbose_name='Почта')

    def __str__(self):
        return f'{self.first_name}, {self.last_name}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    photo = models.ImageField(**NULLABLE, upload_to='category/', verbose_name='Фото')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Порода'
        verbose_name_plural = 'Породы'


class Dog(models.Model):
    name = models.CharField(max_length=50, verbose_name='Кличка')
    age = models.IntegerField(**NULLABLE, verbose_name='Возраст')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    photo = models.ImageField(**NULLABLE, upload_to='dog/', verbose_name='Фото')
    price = models.IntegerField(verbose_name='Стоимость')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Порода')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Собака'
        verbose_name_plural = 'Собаки'


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.SlugField(max_length=50, verbose_name='slug')
    content = models.TextField(verbose_name='Содержимое')
    photo = models.ImageField(**NULLABLE, upload_to='blog_previews/', verbose_name='Превью')
    view_count = models.IntegerField(default=0, verbose_name='Просмотры')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    published = models.BooleanField(default=False, verbose_name='Публикация')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

zooApp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from transliterate import translit
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from zooApp.models import Category, Dog, Blog


class CategoryListView(ListView):
    """Наследовался от модели Category"""
    model = Category
    """Указал максимальное кол-во карточек на странице (в CBV передает page_obj в контексте под капотом)"""
    paginate_by = 10
    """Функция для передачи доп информации (контекста) в шаблон"""

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        """Добавили поле title и вернули с помощью return"""
        context['title'] = 'Породы'
        return context


"""Класс для создания породы"""


class CategoryCreateView(CreateView):
    model = Category
    """Поля для которые нужно заполнить при создании"""
    fields = ('name', 'description', 'photo')
    """Ссылка по умолчанию по которой пользователь будет переходить после создания породы"""
    success_url = reverse_lazy('zooApp:category')


"""Класс для редактирования породы"""


class CategoryUpdateView(UpdateView):
    model = Category
    fields = ('name', 'description', 'photo')
    success_url = reverse_lazy('zooApp:category')


"""Класс удаление породы"""


class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('zooApp:category')


"""Метод ссылающийся на шаблон настройки"""


def settings(request):
    context = {
        'title': 'Настройки'
    }
    return render(request, 'zooApp/settings.html')


"""Список собак"""


class DogsListView(ListView):
    model = Dog
    paginate_by = 10

    """Передача контекста"""

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Собаки'
        return context

    def get_queryset(self):
        """Извлекаем значение первичного ключа"""
        category_pk = self.kwargs['pk']
        """Выполняем запрос к модели Dog и фильтруем по pk"""
        return Dog.objects.filter(category__pk=category_pk)


"""Класс выводит конкретную собаку"""


class DogDetailView(DetailView):
    model = Dog


class DogCreateView(CreateView):
    model = Dog
    fields = ('name', 'age', 'description', 'photo', 'price', 'category')

    success_url = reverse_lazy('zooApp:dog_detail')

    """Метод передает pk для того что бы мы могли попасть в карточку только что созданной собаки"""

    def get_success_url(self):
        """Получаем pk"""
        object_id = self.object.pk
        """Передаем pk переходя по url"""
        detail_url = reverse_lazy('zooApp:dog_detail', kwargs={'pk': object_id})
        return detail_url


class DogUpdateView(UpdateView):
    model = Dog
    fields = ('name', 'age', 'description', 'photo', 'price', 'category')
    success_url = reverse_lazy('zooApp:dog_detail')

    def get_success_url(self):
        object_id = self.object.pk
        detail_url = reverse_lazy('zooApp:dog_detail', kwargs={'pk': object_id})
        return detail_url


class DogDeleteView(DeleteView):
    model = Dog
    success_url = reverse_lazy('zooApp:category')


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'photo', 'published',)
    success_url = reverse_lazy('zooApp:detail_blog')

    def get_success_url(self):
        object_id = self.object.pk
        detail_url = reverse_lazy('zooApp:detail_blog', kwargs={'pk': object_id})
        return detail_url


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'photo', 'published',)
    success_url = reverse_lazy('zooApp:detail_blog')

    def get_success_url(self):
        object_id = self.object.pk
        detail_url = reverse_lazy('zooApp:detail_blog', kwargs={'pk': object_id})
        return detail_url


class BlogListView(ListView):
    model = Blog
    template_name = 'zooApp/main_list_true.html'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная Страница'

        return context


"""Класс для не опубликованных блогов"""


class BlogUnpublishedListView(ListView):
    model = Blog
    paginate_by = 10
    template_name = 'zooApp/blog_unpublished.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Не опубликовано'
        return context


class BlogDetailView(DetailView):
    model = Blog

    """Метод для отслеживания просмотров"""

    def get(self, request, *args, **kwargs):
        blog = self.get_object()

        # Увеличиваем счетчик просмотров
        blog.view_count += 1
        blog.save()

        return super().get(request, *args, **kwargs)

    """Создание человекочитаймого slug переводит с русского языка на английский"""

    def create_slug(self, title):
        return translit(title, 'ru', reversed=True)

    def get_queryset(self):
        queryset = super().get_queryset()
        for blog in queryset:
            blog.slug = self.create_slug(blog.title)
            blog.save()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Публикация'
        return context


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('zooApp:main')

zooApp/templates/zooApp/includes/inc_delete.html
<div class="container">
    <main>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-5">
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Удаление</h4>
                    <form class="needs-validation" novalidate>

                        <hr class="my-4">
                        <p>Вы действительно хотите удалить "{{ object.name }}"?</p>

                        <button class="btn btn-danger btn-lg" type="submit">Удалить</button>
                        <a href="{% url 'zooApp:main'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </form>
    </main>
</div>

zooApp/templates/zooApp/includes/inc_form.html
<div class="container">
    <main>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-5">

                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Редактирование</h4>
                    <form class="needs-validation" novalidate>
                        {{ form.as_p }}

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif%}
                        </button>
                    </form>

                </div>
            </div>
        </form>
    </main>
</div>

zooApp/templates/zooApp/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Меню</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:main' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:category' %}">Породы</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'zooApp:settings' %}">Настройки</a>
    </nav>

</div>

zooApp/templates/zooApp/includes/inc_paginate.html
{% for contact in page_obj %}
    {{ contact.full_name|upper }}<br>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>

zooApp/templates/zooApp/includes/inc_view.html
{% load my_tags %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"></h1>
</div>
<div class="container">
    <h1>Породы</h1>
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <img src="{{ object.photo|mymedia }}" width="200" height="200">
                    <a href="" class="btn btn-lg btn-block btn-outline-primary">Перейти</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>